# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Firebase Hosting on merge

on:
  # Runs on pushes targeting the default branch
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'           # Push events to every tag not containing /

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    if: github.repository == 'UCLA-IRL/ndn-workspace-solid'
    environment:
      name: firebase
      url: https://ndn-workspace.web.app/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: |
            - args: [--no-frozen-lockfile]
      - name: Build
        run: pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NDN_WORKSPACE }}"
          channelId: live
          projectId: ndn-workspace
